---
- name: Include checks/asserts
  import_tasks: asserts.yml

- name: Install OS package
  package:
    name: dnsmasq
    state: present

- name: Create configuration
  template:
    src: dnsmasq.conf.j2
    dest: /etc/dnsmasq.conf
    owner: root
    group: root
    mode: "0644"
    validate: "dnsmasq --test --conf-file=%s"
  notify:
    - restart dnsmasq

- name: Start and enable service
  service:
    name: dnsmasq
    state: started
    enabled: yes

- name: "Wait for service to became available on port {{ dnsmasq_port }}"
  wait_for:
    port: "{{ dnsmasq_port|int }}"
    timeout: 30
  when:
    - dnsmasq_port|int > -1
