---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint tasks/*.yml
  flake8
platforms:
  - name: debian--10
    image: debian:10
    capabilities:
      - NET_ADMIN
  # - name: instance
  #   image: docker.io/pycontribs/centos:7
  #   pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
